### ISSUE TITLE
Text and some icons in the UI not displaying properly

### ISSUE THREAD

**Issue by MrFellox** [delrius-euphoria/PassLost#1]
These errors are just visual problems, text and some icons seem like they are being cutted out.

### Screenshots

![](https://i.imgur.com/xyQrFHZ.png)

![](https://i.imgur.com/WMU0TKd.png)

**Comment by nihaalnz** [comment]
Hi, thanks for the feedback. I did not make this app to be responsive to different dimension(I should've). Anyway what is the resolution of your screen?

**Comment by nihaalnz** [comment]
I have tested this on 3 devices of 1920x1080 display but I was not able to reciprocate the clipping of icons, anyway I am assuming it is because of the zoom, anyway I will try to make the UI responsive :D

**Comment by MrFellox** [comment]
Sounds good, and yes, just checked and its because of zoom. Just a minor bug, it doesn't really affect user experience.

**Comment by nihaalnz** [comment]
@MrFellox Can you check if the new version works without the issue mentioned here? You might want to uninstall the previous version and install this.
